# Generated by Django 4.2 on 2023-04-23 08:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("school", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="examassign",
            name="is_done",
            field=models.BooleanField(default=False),
        ),
    ]
