# Generated by Django 4.2 on 2023-04-24 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("school", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="class",
            name="class_teacher",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="school.teacher",
            ),
        ),
        migrations.AlterField(
            model_name="class",
            name="description",
            field=models.TextField(
                help_text="eg: 'Class 6, total 120 students, 4 sections, 30 students in each section'"
            ),
        ),
    ]
