# Generated by Django 4.2 on 2023-05-02 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("school", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="section",
            name="class_teacher",
        ),
        migrations.AddField(
            model_name="section",
            name="section_teacher",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="school.teacher",
                verbose_name="Section Teacher",
            ),
        ),
    ]
