# Generated by Django 4.2 on 2023-05-02 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("school", "0002_remove_section_class_teacher_section_section_teacher"),
    ]

    operations = [
        migrations.AlterField(
            model_name="section",
            name="section_teacher",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="school.teacher",
                verbose_name="Section Teacher",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="sectionsubject",
            unique_together={("teachers", "section", "period")},
        ),
    ]
