# Generated by Django 4.2 on 2023-04-24 11:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("school", "0002_class_class_teacher_alter_class_description"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="student",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="studentassign",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="studentassign",
            name="class_roll",
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterUniqueTogether(
            name="studentassign",
            unique_together={("student", "section", "class_roll")},
        ),
        migrations.RemoveField(
            model_name="student",
            name="class_roll",
        ),
        migrations.RemoveField(
            model_name="student",
            name="section",
        ),
    ]
