# Generated by Django 4.2 on 2023-05-05 19:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("school", "0002_alter_class_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subject",
            name="description",
            field=models.TextField(
                blank=True, default="", help_text="Subject Description", null=True
            ),
        ),
    ]
