# Generated by Django 4.2.4 on 2023-11-08 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_alter_class_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='description',
            field=models.CharField(blank=True, help_text='Section Description, e.g. Section A of Class 6, total 30 students ', max_length=255, null=True),
        ),
    ]
