# Generated by Django 4.2 on 2023-04-26 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("school", "0002_alter_studentassign_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentassign",
            name="student",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="student_assignments",
                to="school.student",
            ),
        ),
    ]
