# Generated by Django 4.2.4 on 2023-10-31 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_alter_class_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ('-created_at',), 'verbose_name_plural': 'Students'},
        ),
        migrations.RenameField(
            model_name='class',
            old_name='class_teacher',
            new_name='teacher',
        ),
    ]
