# Generated by Django 4.2.4 on 2023-11-02 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_alter_student_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacher',
            options={'ordering': ('-created_at',), 'verbose_name_plural': 'Teachers'},
        ),
        migrations.RenameField(
            model_name='section',
            old_name='section_teacher',
            new_name='teacher',
        ),
        migrations.AlterField(
            model_name='teacher',
            name='photo',
            field=models.ImageField(blank=True, help_text='Recommended: Upload 1:1 ratio image', null=True, upload_to='teacher_photo'),
        ),
    ]
