# Generated by Django 4.2 on 2023-05-05 19:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("school", "0003_alter_subject_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="class",
            name="description",
            field=models.TextField(
                blank=True,
                default="",
                help_text="eg: 'Class 6, total 120 students, 4 sections, 30 students in each section'",
                null=True,
            ),
        ),
    ]
