# Generated by Django 4.2 on 2023-04-26 19:03

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("school", "0003_alter_studentassign_student"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="attendance",
            options={},
        ),
        migrations.AlterUniqueTogether(
            name="studentassign",
            unique_together={("section", "class_roll")},
        ),
        migrations.AddField(
            model_name="attendance",
            name="student_assign",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attendance",
                to="school.studentassign",
            ),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="date",
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterUniqueTogether(
            name="attendance",
            unique_together={("student_assign", "date")},
        ),
        migrations.RemoveField(
            model_name="attendance",
            name="student",
        ),
    ]
