# Generated by Django 4.2.4 on 2023-11-03 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_alter_teacher_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sectionsubject',
            old_name='teachers',
            new_name='teacher',
        ),
        migrations.AlterUniqueTogether(
            name='sectionsubject',
            unique_together={('teacher', 'section', 'period')},
        ),
    ]
