# Generated by Django 4.2 on 2023-04-26 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("school", "0004_alter_attendance_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendance",
            name="student_assign",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attendance",
                to="school.studentassign",
            ),
        ),
    ]
