# Generated by Django 4.2 on 2023-04-24 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "school",
            "0004_rename_photo_student_image_student_admission_section_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="admission_section",
        ),
        migrations.AddField(
            model_name="student",
            name="admission_class",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="school.class",
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="admission_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="student",
            name="dob",
            field=models.DateField(blank=True, null=True),
        ),
    ]
