# Generated by Django 4.2.4 on 2023-11-08 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_alter_section_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='seat',
            field=models.PositiveIntegerField(default=45),
        ),
    ]
