# Generated by Django 4.2.4 on 2023-11-10 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_alter_section_seat'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='attendance',
            name='student',
            field=models.ForeignKey(default=3434343, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_student', to='school.studentassign'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('student', 'date')},
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='student_assign',
        ),
    ]
