# Generated by Django 4.2 on 2023-04-28 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("school", "0005_alter_attendance_student_assign"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendance",
            name="student_assign",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attendance",
                to="school.studentassign",
            ),
        ),
        migrations.AlterField(
            model_name="studentassign",
            name="section",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="section",
                to="school.section",
            ),
        ),
        migrations.AlterField(
            model_name="studentassign",
            name="student",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="student",
                to="school.student",
            ),
        ),
    ]
