# Generated by Django 4.2 on 2023-04-24 14:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("school", "0005_remove_student_admission_section_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="fathers_nid",
            field=models.CharField(blank=True, max_length=17, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="student",
            name="mothers_nid",
            field=models.CharField(blank=True, max_length=17, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="student",
            name="name_bn",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="student",
            name="student_id",
            field=models.CharField(blank=True, max_length=7, unique=True),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="dob",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="joining_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="name_bn",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterUniqueTogether(
            name="student",
            unique_together={("student_id", "birth_certificate_no")},
        ),
        migrations.AlterUniqueTogether(
            name="teacher",
            unique_together={("teacher_id", "nid")},
        ),
    ]
