# Generated by Django 4.2.4 on 2023-11-05 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_rename_teachers_sectionsubject_teacher_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='description',
        ),
    ]
