# Generated by Django 4.2 on 2023-05-06 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("school", "0005_alter_section_description"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="attendance",
            options={"ordering": ["-date"]},
        ),
        migrations.AlterUniqueTogether(
            name="attendance",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="student_attendance",
                to="school.student",
            ),
        ),
        migrations.AlterField(
            model_name="studentassign",
            name="student",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="student_assign",
                to="school.student",
            ),
        ),
        migrations.CreateModel(
            name="StudentGrade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cq_marks", models.CharField(blank=True, max_length=2, null=True)),
                ("mcq_marks", models.CharField(blank=True, max_length=2, null=True)),
                (
                    "practical_marks",
                    models.CharField(blank=True, max_length=2, null=True),
                ),
                (
                    "obtained_marks",
                    models.CharField(blank=True, max_length=2, null=True),
                ),
                (
                    "section_subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="section_subject",
                        to="school.sectionsubject",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_grade",
                        to="school.studentassign",
                    ),
                ),
            ],
            options={
                "ordering": ["student"],
            },
        ),
    ]
