# Generated by Django 4.2 on 2023-04-28 16:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("school", "0006_alter_attendance_student_assign_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="section",
            old_name="total_students",
            new_name="seat",
        ),
    ]
