# Generated by Django 4.2.4 on 2023-11-05 18:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_remove_subject_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectionsubject',
            name='period',
            field=models.IntegerField(default=0, unique=True, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)]),
        ),
    ]
