# Generated by Django 4.2 on 2023-05-06 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("school", "0006_alter_attendance_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendance",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="student_attendance",
                to="school.studentassign",
            ),
        ),
    ]
