# Generated by Django 4.2 on 2023-04-28 18:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("school", "0007_rename_total_students_section_seat"),
    ]

    operations = [
        migrations.AddField(
            model_name="sectionsubject",
            name="period",
            field=models.IntegerField(default=0),
        ),
    ]
