# Generated by Django 4.2 on 2023-05-06 17:04

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("school", "0007_alter_attendance_student"),
    ]

    operations = [
        migrations.CreateModel(
            name="Exam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("exam_title", models.CharField(max_length=255)),
                ("exam_start_date", models.DateField(blank=True, null=True)),
                ("exam_end_date", models.DateField(blank=True, null=True)),
                ("exam_time", models.TimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="ExamAssign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "question_paper",
                    models.FileField(blank=True, null=True, upload_to="question_paper"),
                ),
                (
                    "full_mark",
                    models.IntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MaxValueValidator(100),
                            django.core.validators.MinValueValidator(0),
                        ],
                    ),
                ),
                (
                    "pass_mark",
                    models.IntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MaxValueValidator(100),
                            django.core.validators.MinValueValidator(0),
                        ],
                    ),
                ),
                ("exam_date", models.DateField(blank=True, null=True)),
                ("exam_time", models.TimeField(blank=True, null=True)),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="school.exam"
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="school.section"
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="school.sectionsubject",
                    ),
                ),
            ],
            options={
                "unique_together": {("exam", "section", "subject")},
            },
        ),
        migrations.DeleteModel(
            name="StudentGrade",
        ),
    ]
