# Generated by Django 4.2 on 2023-05-06 17:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("school", "0008_exam_examassign_delete_studentgrade"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="exam",
            name="exam_end_date",
        ),
        migrations.RemoveField(
            model_name="exam",
            name="exam_start_date",
        ),
        migrations.AddField(
            model_name="exam",
            name="exam_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="exam",
            name="exam_title",
            field=models.CharField(
                choices=[
                    ("Half Yearly", "Half Yearly"),
                    ("Final", "Final"),
                    ("Test", "Test"),
                    ("Pre-Test", "Pre-Test"),
                ],
                max_length=255,
            ),
        ),
    ]
