# Generated by Django 4.2.4 on 2023-11-15 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0008_alter_attendance_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'ordering': ['date']},
        ),
    ]
