# Generated by Django 4.2 on 2023-04-28 18:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("school", "0008_sectionsubject_period"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sectionsubject",
            name="period",
            field=models.IntegerField(
                default=0,
                validators=[
                    django.core.validators.MaxValueValidator(10),
                    django.core.validators.MinValueValidator(0),
                ],
            ),
        ),
    ]
