# Generated by Django 4.2.4 on 2023-11-15 17:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0009_alter_attendance_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='OffDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('reason', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('date',)},
            },
        ),
    ]
