# Generated by Django 4.2.4 on 2023-08-23 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0009_remove_exam_exam_end_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='student',
            new_name='student_assign',
        ),
    ]
