# Generated by Django 4.2.4 on 2023-11-06 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0009_remove_guardian_relation_studentguardian_relation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='guardians',
        ),
        migrations.AddField(
            model_name='guardian',
            name='relation',
            field=models.CharField(choices=[('Father', 'Father'), ('Mother', 'Mother'), ('Guardian', 'Guardian')], default='Guardian', max_length=8),
        ),
        migrations.AddField(
            model_name='student',
            name='guardian',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guardian', to='school.guardian'),
        ),
        migrations.DeleteModel(
            name='StudentGuardian',
        ),
    ]
