# Generated by Django 4.2 on 2023-04-29 06:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("school", "0009_alter_sectionsubject_period"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="sectionsubject",
            options={"ordering": ["period"]},
        ),
        migrations.AddField(
            model_name="sectionsubject",
            name="time",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
