# Generated by Django 4.2 on 2023-04-29 16:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("school", "0010_alter_sectionsubject_options_sectionsubject_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendance",
            name="date",
            field=models.DateField(default=datetime.date.today, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name="sectionsubject",
            unique_together={("section", "period", "time")},
        ),
    ]
