# Generated by Django 4.2.4 on 2023-11-16 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0010_offday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examassign',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.sectionsubject'),
        ),
        migrations.DeleteModel(
            name='ExamSubject',
        ),
    ]
