# Generated by Django 4.2.4 on 2023-08-28 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0011_result'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark_obtained', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='examassign',
            name='full_mark',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='examassign',
            name='pass_mark',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Result',
        ),
        migrations.AddField(
            model_name='studentresult',
            name='exam_assign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.examassign'),
        ),
        migrations.AddField(
            model_name='studentresult',
            name='student_assign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.studentassign'),
        ),
        migrations.AlterUniqueTogether(
            name='studentresult',
            unique_together={('student_assign', 'exam_assign')},
        ),
    ]
