# Generated by Django 4.2.4 on 2023-11-06 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0011_rename_first_name_guardian_name_bn_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guardian',
            name='name_bn',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
