# Generated by Django 4.2.4 on 2023-11-16 19:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0011_alter_examassign_subject_delete_examsubject'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sectionsubject',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='sectionsubject',
            name='period',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterUniqueTogether(
            name='sectionsubject',
            unique_together={('section', 'period')},
        ),
    ]
