# Generated by Django 4.2.4 on 2023-11-16 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0012_alter_sectionsubject_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examassign',
            name='teacher',
        ),
    ]
