# Generated by Django 4.2.4 on 2023-08-28 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0012_studentresult_alter_examassign_full_mark_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='examassign',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='examassign',
            name='exam',
        ),
        migrations.RemoveField(
            model_name='examassign',
            name='section',
        ),
        migrations.RemoveField(
            model_name='examassign',
            name='subject',
        ),
        migrations.AlterUniqueTogether(
            name='studentresult',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='studentresult',
            name='exam_assign',
        ),
        migrations.RemoveField(
            model_name='studentresult',
            name='student_assign',
        ),
        migrations.DeleteModel(
            name='Exam',
        ),
        migrations.DeleteModel(
            name='ExamAssign',
        ),
        migrations.DeleteModel(
            name='StudentResult',
        ),
    ]
