# Generated by Django 4.2.4 on 2023-11-16 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0013_remove_examassign_teacher'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='exam',
            unique_together={('exam_type', 'year')},
        ),
    ]
