# Generated by Django 4.2.4 on 2023-11-17 14:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0014_alter_exam_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='examassign',
            old_name='exam_time',
            new_name='time',
        ),
        migrations.AddField(
            model_name='examassign',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
