# Generated by Django 4.2.4 on 2023-08-29 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0014_exam_examassign_studentresult'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='examassign',
            unique_together={('exam', 'subject')},
        ),
        migrations.RemoveField(
            model_name='examassign',
            name='section',
        ),
    ]
