# Generated by Django 4.2.4 on 2023-11-17 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0015_rename_exam_time_examassign_time_examassign_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='slug',
            field=models.SlugField(default='NULL', unique=True),
            preserve_default=False,
        ),
    ]
