# Generated by Django 4.2.4 on 2023-08-29 17:33

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0016_alter_subject_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examassign',
            name='exam_time',
            field=models.TimeField(blank=True, help_text='Exam Time', null=True),
        ),
        migrations.AlterField(
            model_name='examassign',
            name='full_mark',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='examassign',
            name='pass_mark',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='studentresult',
            name='exam_assign',
            field=models.ForeignKey(help_text='Exam Assign', on_delete=django.db.models.deletion.CASCADE, to='school.examassign'),
        ),
        migrations.AlterField(
            model_name='studentresult',
            name='mcq_mark',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='studentresult',
            name='practical_mark',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='studentresult',
            name='student_assign',
            field=models.ForeignKey(help_text='Student Assign', on_delete=django.db.models.deletion.CASCADE, to='school.studentassign'),
        ),
        migrations.AlterField(
            model_name='studentresult',
            name='written_mark',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
    ]
