# Generated by Django 4.2.4 on 2023-08-29 17:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0018_alter_studentresult_practical_mark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentresult',
            name='practical_mark',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
    ]
