# Generated by Django 4.2.4 on 2023-08-29 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0020_alter_studentresult_practical_mark'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
