# Generated by Django 4.2.4 on 2023-08-29 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0021_class_slug_exam_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='title',
            field=models.CharField(choices=[('Class-6', 'Six'), ('Class-7', 'Seven'), ('Class-8', 'Eight'), ('Class-9', 'Nine'), ('Class-10', 'Ten')], max_length=8, primary_key=True, serialize=False),
        ),
    ]
