# Generated by Django 4.2.4 on 2023-08-30 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0024_examsubject_alter_examassign_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='examsubject',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='school.teacher'),
        ),
    ]
