# Generated by Django 4.2.4 on 2023-08-30 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0025_examsubject_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examsubject',
            name='teacher',
        ),
        migrations.AddField(
            model_name='examassign',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='school.teacher'),
        ),
    ]
