# Generated by Django 4.2.4 on 2023-08-30 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0026_remove_examsubject_teacher_examassign_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='examassign',
            name='year',
            field=models.CharField(default=2021, max_length=4),
            preserve_default=False,
        ),
    ]
