# Generated by Django 4.2.4 on 2023-08-30 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0027_examassign_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examassign',
            name='year',
        ),
        migrations.AddField(
            model_name='exam',
            name='year',
            field=models.CharField(default=2021, max_length=4),
            preserve_default=False,
        ),
    ]
