# Generated by Django 4.2.4 on 2023-10-14 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0029_alter_attendance_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='examassign',
            options={'ordering': ['exam', 'subject']},
        ),
    ]
