# Generated by Django 4.2.4 on 2023-10-16 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagegallery',
            options={'verbose_name_plural': 'Image Gallery'},
        ),
    ]
