# Generated by Django 4.2.4 on 2023-10-20 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_rename_images_imagegallery_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagegallery',
            old_name='image',
            new_name='url',
        ),
    ]
