# Generated by Django 4.2.4 on 2023-10-20 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_rename_image_imagegallery_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagegallery',
            old_name='url',
            new_name='image',
        ),
    ]
