# Generated by Django 4.2.4 on 2023-10-17 08:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_notice_created_at_alter_notice_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='attachment',
            field=models.FileField(blank=True, help_text='Upload Your Notice PDF or Docs', null=True, upload_to='notices/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'docx'])]),
        ),
        migrations.AlterField(
            model_name='notice',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
