# Generated by Django 4.2.4 on 2023-10-18 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_alter_contact_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usefullink',
            old_name='title',
            new_name='site',
        ),
        migrations.RemoveField(
            model_name='usefullink',
            name='description',
        ),
        migrations.RemoveField(
            model_name='usefullink',
            name='slug',
        ),
    ]
