# Generated by Django 4.2.4 on 2023-10-17 08:29

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('homepage', '0004_alter_notice_attachment_alter_notice_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='tag',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
