# Generated by Django 4.2.4 on 2023-10-20 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_rename_url_imagegallery_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stat',
            name='description',
        ),
    ]
