# Generated by Django 4.2.4 on 2023-10-18 18:33

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_contact_map'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notice',
            options={'ordering': ['-date'], 'verbose_name_plural': 'Notices'},
        ),
        migrations.AlterField(
            model_name='contact',
            name='map',
            field=models.TextField(help_text="<b style='color: red'> Copy and Paste google map's <em> iframe </em> tag here </b>"),
        ),
        migrations.AlterField(
            model_name='notice',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
