# Generated by Django 4.2.4 on 2023-10-20 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_remove_stat_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='stat',
            name='icon',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
