# Generated by Django 4.2.4 on 2023-10-17 18:18

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('homepage', '0005_notice_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notice',
            name='tag',
        ),
        migrations.AddField(
            model_name='notice',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
