# Generated by Django 4.2.4 on 2023-10-20 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0006_stat_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='whatshappening',
            name='url',
        ),
        migrations.AlterField(
            model_name='stat',
            name='icon',
            field=models.CharField(blank=True, help_text='<em> Add font-awesome icon tag </em>', max_length=200, null=True),
        ),
    ]
