# Generated by Django 4.2.4 on 2023-10-18 06:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0006_remove_notice_tag_notice_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='governancebody',
            name='designation',
            field=models.CharField(default='Member', max_length=200),
        ),
        migrations.AlterField(
            model_name='governancebody',
            name='speech_file',
            field=models.FileField(blank=True, help_text='Upload Speech PDF or Docs', null=True, upload_to='governance_bodies/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'docx', 'doc'])]),
        ),
        migrations.AlterField(
            model_name='notice',
            name='attachment',
            field=models.FileField(blank=True, help_text='Upload Your Notice PDF or Docs', null=True, upload_to='notices/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'docx', 'doc'])]),
        ),
    ]
