# Generated by Django 4.2.4 on 2023-10-18 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0007_governancebody_designation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='governancebody',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='governancebody',
            name='speech_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
