# Generated by Django 4.2.4 on 2023-10-20 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0008_whatshappening_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatshappening',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
