# Generated by Django 4.2.4 on 2023-10-20 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0009_alter_whatshappening_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatshappening',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
