# Generated by Django 4.2.4 on 2023-10-20 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0011_bannerimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dropdownnavigationitem',
            name='slug',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
