# Generated by Django 4.2.4 on 2023-10-21 06:23

import ckeditor_uploader.fields
import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0012_alter_dropdownnavigationitem_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_history', models.CharField(max_length=200)),
                ('description_history', ckeditor_uploader.fields.RichTextUploadingField()),
                ('slug', models.SlugField()),
                ('title_mission', models.CharField(max_length=200)),
                ('description_mission', ckeditor_uploader.fields.RichTextUploadingField()),
                ('created_at_mission', models.DateField(auto_now_add=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='brightstudent',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Bright Students'},
        ),
        migrations.AlterModelOptions(
            name='cocurricular',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Co-Curricular'},
        ),
        migrations.AlterModelOptions(
            name='governancebody',
            options={'ordering': ['-id'], 'verbose_name_plural': 'Governance Bodies'},
        ),
        migrations.AlterModelOptions(
            name='imagegallery',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Image Gallery'},
        ),
        migrations.AlterModelOptions(
            name='usefullink',
            options={'ordering': ['-id'], 'verbose_name_plural': 'Useful Links'},
        ),
        migrations.AlterModelOptions(
            name='whatshappening',
            options={'ordering': ['-date'], 'verbose_name_plural': "What's Happening"},
        ),
        migrations.AddField(
            model_name='brightstudent',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2023, 10, 21, 6, 21, 14, 117000, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cocurricular',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cocurricular',
            name='image',
            field=models.ImageField(default='media/default.png', upload_to='co_curricular/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imagegallery',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cocurricular',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
