# Generated by Django 4.2.4 on 2023-10-23 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0015_alter_governancebody_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='governancebody',
            name='description',
            field=models.CharField(blank=True, help_text='15 words max', max_length=500, null=True),
        ),
    ]
