# Generated by Django 4.2.4 on 2023-10-26 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0017_alter_notice_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='slug',
            field=models.SlugField(blank=True, default='djangodbmodelsfieldscharfielddatedjangodbmodelsfieldsdatefield', null=True, unique=True),
        ),
    ]
